import Head from "next/head";
import { useEffect, useState } from "react";

export default function Home() {
  const [greeting, setGreeting] = useState();

  useEffect(() => {
    async function fetchData() {
      const { text } = await (await fetch("/api/hello")).json();

      setGreeting(text);
    }

    fetchData();
  }, []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>{greeting}</h1>
      </main>
    </div>
  );
}
